### ISSUE TITLE
Server does not start W7 and W10

### ISSUE THREAD

**Issue by melvincoin** [JupiterDevelopmentTeam/JupiterX#2]
Exited to test JupiterX but the server does not start (starting from scratch):

C:\Users\Melvin\Desktop\JupiterX>"C:\Program Files\Java\jre1.8.0_161\bin\java.exe" -jar JupiterX-1.0-SNAPSHOT.jar
Starting JupiterX server for Minecraft...

And it does not start further. Tested on two server pc's. 

My start.bat contains:
"C:\Program Files\Java\jre1.8.0_161\bin\java.exe" -jar JupiterX-1.0-SNAPSHOT.jar
pause 
(renamed the file from jupiterx-1.0-ALPHA.jar to JupiterX-1.0-SNAPSHOT.jar)

**Comment by itsu020402** [comment]
Thank you for using.
This project was started few weeks ago.
So this program has not completed to host your server.
